name: terraform-provider-pulsar -> Acceptance Tests
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install terraform@1.1.9
        run: |
          wget https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip
          unzip terraform_1.1.9_linux_amd64.zip && sudo mv terraform /usr/local/bin
          mkdir -p $HOME/.terraform.d/plugins/linux_amd64
          export TF_ACC_TERRAFORM_PATH=/usr/local/bin/terraform

      - name: Run pulsar standalone in Docker
        run: make run-pulsar-in-docker

      - name: Building the terraform-provider-pulsar
        run: |
          make tools
          make build
          sudo mv terraform-provider-pulsar $HOME/.terraform.d/plugins/linux_amd64/
          echo "looking for terraform provider -> pulsar: " && ls $HOME/.terraform.d/plugins/linux_amd64/

      - name: Running Acceptance Tests for the Proivder on Standalone Instance
        run: |
          docker ps
          make testacc

      - name: Remove pulsar standalone from Docker
        run: make remove-pulsar-from-docker

