name: terraform-provider-pulsar -> Acceptance Tests
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          wget https://releases.hashicorp.com/terraform/0.12.17/terraform_0.12.17_linux_amd64.zip
          unzip terraform_0.12.17_linux_amd64.zip && sudo mv terraform /usr/local/bin
          docker run -d -p 6650:6650 -p 8080:8080 -v $PWD/data:/pulsar/data apachepulsar/pulsar:2.8.1 bin/pulsar standalone
          mkdir -p $HOME/.terraform.d/plugins/linux_amd64
          until curl http://localhost:8080/admin/v2/tenants > /dev/null 2>&1
          do
              sleep 1
              echo "Wait for pulsar service to be ready...$(date +%H:%M:%S)"
          done
          echo "Pulsar service is ready"

      - name: Building the terraform-provider-pulsar
        run: |
          make tools
          make build
          sudo mv terraform-provider-pulsar $HOME/.terraform.d/plugins/linux_amd64/
          echo "looking for terraform provider -> pulsar: " && ls $HOME/.terraform.d/plugins/linux_amd64/

      - name: Running Acceptance Tests for the Proivder on Standalone Instance
        run: |
          docker ps
          make testacc
