name: terraform-provider-pulsar -> Code Style & Linter check
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint-action@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1

      - name: Linter Check
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1
          curl -sSfL https://github.com/bflad/tfproviderlint/releases/download/v0.27.1/tfproviderlint_0.27.1_linux_amd64.tar.gz | tar -zx -C $(go env GOPATH)/bin -f - tfproviderlint
          echo "looking for golangci-lint" && whereis golangci-lint
          echo "looking for tfproviderlint" && whereis tfproviderlint
          make lint
