name: terraform-provider-pulsar -> Code Style & Linter check
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint-action@v2
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46.2

      - name: Linter Check
        run: |
          make tools
          echo "looking for linter" && whereis golangci-lint
          golangci-lint run -c ./.golangci.yaml ./...
